# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
    # Update to R3.6 repo
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
    # install base deps
    apt-get update
    apt-get install -y mariadb-server git r-base
    # install r system deps
    apt-get install -y libcurl4-openssl-dev libxml2-dev libmariadbclient-dev

    cp /vagrant/.my.cnf ~/.my.cnf

    mariadb -u root -p='' -e "CREATE DATABASE txronaparser;"
    mariadb -u root -p='' -e "GRANT ALL PRIVILEGES ON txronaparser.* TO 'txronaparser'@'localhost' IDENTIFIED BY 'some_pass';"
    mariadb -u root -p='' -e "FLUSH PRIVILEGES;"

    R -f /vagrant/runner.R
  SHELL
end
