version: "3.3"
services:
  mariadb:
    image: mariadb:10.5.3 
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rona
      MYSQL_USER: grafana
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: "host"
    restart: always

  txronaparser:
    image: 557349407515.dkr.ecr.us-east-2.amazonaws.com/txronaparser:0.3
    container_name: txronaparser
    network_mode: "host"
